name: Website CI CD

################################################################
# Only do this when on the website-ui branch for now
################################################################

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  build:
    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install node modules
      run: npm ci
    - name: Precompile Handlebars files
      run: npm run handlebars
    - name: Create JavaScript file
      run: npm run webpack
    - name: Copy the created JavaScript file
      run: cp ./dist/main.js ./website/main.js
    - name: Copy best programs data
      run: cp ./best_programs.json ./website/best_programs.json
    - name: Remove the TypeScript source files
      run: |
        rm ./website/main.ts
        rm -rf ./website/src/
    - name: Remove the Handlebars source files
      run: rm -rf ./website/handlebars
    - name: Temporarily save created "website" files
      uses: actions/upload-artifact@v4
      with:
        name: website-artifacts
        path: ./website
        retention-days: 7

  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'pull_request'
    needs:
    - build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v5
    - name: Retrieve temporarily saved "website" files from the build job
      uses: actions/download-artifact@v4
      with:
        name: website-artifacts
        path: bin
    - uses: actions/upload-pages-artifact@v1
      with:
        path: bin
    - uses: actions/deploy-pages@v1
      id: deployment
