name: Website CI CD

################################################################
# Only do this when on the website-ui branch for now
################################################################

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ website-ui ]
  pull_request:
    branches: [ website-ui ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node modules
      run: npm ci
    - name: Precompile Handlebars files
      run: npm run handlebars
    - name: Create JavaScript file
      run: npm run webpack
    - name: Copy the created JavaScript file
      run: cp ./dist/main.js ./website/main.js
    - name: Copy best programs data
      run: cp ./best_programs.json ./website/best_programs.json
    - name: Remove the TypeScript source files
      run: |
        rm ./website/main.ts
        rm -rf ./website/src/
    - name: Remove the Handlebars source files
      run: rm -rf ./website/handlebars
    - name: Temporarily save created "website" files
      uses: actions/upload-artifact@v2
      with:
        name: website-artifacts
        path: ./website
        retention-days: 7

  deploy:
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Retrieve temporarily saved "website" files from the build job
      uses: actions/download-artifact@v2
      with:
        name: website-artifacts
        path: ./bin
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
